### PR TITLE
Added CI workflows

### PR DESCRIPTION
**Pull request by krisbitney**

### CODE REVIEW

**Comment by cbrzn** [comment]
Hey guys just curious: What's the status of this? I saw @Niraj-Kamdar's comment here https://github.com/polywrap/monorepo/issues/305#issuecomment-1012232353 and was wondering if this is still in discussion

**Comment by Niraj-Kamdar** [comment]
@cbrzn We came to the conclusion that we would like to have the CI for demos/integrations in their own repo.

**Comment by Niraj-Kamdar** [comment]
I think none is currently working on this. So, if you want to push this to completion then go ahead.

**Comment by krisbitney** [comment]
Is it okay to close this?

**Comment by Niraj-Kamdar** [comment]
yeah it will be replaced by new CI/CD

**Pull request closed without merging**
